### ISSUE TITLE
[REPL] Long text in app titles causing CSS Grid blowout on saved apps list - CSS-only solution provided!

### ISSUE THREAD

**Issue by brandonmcconnell** [sveltejs/sites#320]
Here is how my REPL currently appears, with long text included in the titles of some of my REPLs:

![grid cells overflowing before CSS fix](https://user-images.githubusercontent.com/5913254/160668785-a1a1d01b-9994-42d1-b5fe-13bac111fe1f.png)

By adding these few lines of CSS…
```css
#main header ~ ul > li {
    overflow: hidden;
}

#main header ~ ul > li h2 {
    overflow: hidden;
    text-overflow: ellipsis;
}
```

…the issue is resolved and longer strings that bleed outside their parent are truncated and clipped using an ellipsis.

This is the result:

![grid cells formatted properly after CSS fix](https://user-images.githubusercontent.com/5913254/160668896-01703519-2a8f-41d1-98f4-39bc1e6938dc.png)
