### ISSUE TITLE
body on kit-site is missing font 'Overpass'

### ISSUE THREAD

**Issue by vedam** [sveltejs/sites#35]
Just noticed this while reading the kit-docs.
<img width="414" alt="body-css" src="https://user-images.githubusercontent.com/64245/116043133-8f424e00-a66f-11eb-84f7-4c67a00e8141.png">

So the body on kit-site looks like:
<img width="773" alt="sveltekit body" src="https://user-images.githubusercontent.com/64245/116043206-a84aff00-a66f-11eb-8724-ccfa19d2bcbf.png">

While on the svelte-site we have the 'Overpass' as body-font:
<img width="823" alt="svelte body" src="https://user-images.githubusercontent.com/64245/116043301-c7e22780-a66f-11eb-9d0b-28b83506ea72.png">

**Comment by benmccann** [comment]
The SvelteKit site has a line that's not present on the svelte.dev site:

https://github.com/sveltejs/sites/blob/766775deadec133b90df36878bde18fd423e6552/packages/site-kit/base.css#L63

The svelte.dev site for reference:

https://github.com/sveltejs/site-kit/blob/01d83baee868053b01b560bc92ee34967616113f/base.css#L61

It looks like @Rich-Harris added this in https://github.com/sveltejs/sites/commit/2f03e65da822d07c0f9f0e0ca2eb7127e47e7990

**Comment by benmccann** [comment]
Removing the extra line make it choose a better looking font, but totally screws up the font sizing, so it'll take some tweaking

**Comment by vedam** [comment]
> Removing the extra line make it choose a better looking font, but totally screws up the font sizing, so it'll take some tweaking

I think the extra line is because the custom property `--font`isn't defined elsewhere. (i.e. :root, .theme-default or .typo-default)
I made the base of this css-structure long ago (around svelte 3 upcoming) to my best knowledge.
In the meantime I had to recognized on my personal homepage (using similar techniques) that there seems to be something wrong with the font-shortcut using css-vars (line 139). I guess this is responsible for screwing up font-sizing.

I was able to work around that with either:
```css
/* using a fixed value for line-height – not really what I wanted */
body {
	font: 300 var(--h4)/1.5 var(--font);
	...
}
```
... or splitting the font-shortcut:
```css
body {
	font-family: var(--font);
	font-size: var(--h4);
	line-height: var(--lh);
	font-weight: 300;
	...
}
```
